apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /export/nfs
    server: 172.16.16.200
  persistentVolumeReclaimPolicy: Retain
